### ISSUE TITLE
Encoding issue?

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/VAtools#32]
Hi I'm running the vcf-readcount-annotator.py tool, and it seems that the resulting VCF files have some encoding issues, where the results have %2C, corresponding to ','; for example as follows,
GT:AD:AF:DP:DP4:F1R2:F2R1:FREQ:RD:SB
0/0:164,47:0.22275:211:25%2C61%2C0%2C0:.,.:.,.:0%25:86:.

I've looked at the code, and it seems when I check the entry variable, all is still correct; but when the function vcf_writer.write_record(entry) is called, the written file would start showing %2C. I'm not sure if this is some encoding that has to be specified, or this is an issue with the vcfpy library?

**Comment by susannasiebert** [comment]
This has to do with how the DP4 field is defined in your VCF header. Presumably, it is set to be of Number=1, so the VCF parser we use in VAtools encodes any commas it finds because it assumes that any commas in this field aren't actual separators, but parts of the field value (which should then be encoded). The correct thing would be to fix the VCF header to define the correct number of entries in this field.

**Comment by boyangzhao** [comment]
Ah yes! Thank you!! That was the problem, the DP4 was set to 1 in my VCF header.
