### ISSUE TITLE
Bug in "vcf-genotype-annotator" due to misspelling 

### ISSUE THREAD

**Issue by npatel-ah** [griffithlab/VAtools#39]
Hello, 

I tried running Command `vcf-genotype-annotator strelka2.dna.VEP.Final.vcf Tumor2 "0/1"` and got an error below "

```
Traceback (most recent call last):
  File "/home/miniconda3/envs/pvactools/bin/vcf-genotype-annotator", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/pvactools/lib/python3.7/site-packages/vatools/vcf_genotype_annotator.py", line 67, in main
    entry.FORMAT = entry.FORMAT.appened('GT')
AttributeError: 'list' object has no attribute 'appened'
```

Best, 
Nihir

**Comment by susannasiebert** [comment]
This issue has been fixed in version 4.1.0. This version fixes the error you were seeing when trying to add a dummy sample to your VCF but it also adds the feature to allow adding the GT field to an existing sample. Simply use the existing sample's name as the sample name parameter. Let me know if you run into any error running this new version.
