### ISSUE TITLE
getting error when The INFO field name to use

### ISSUE THREAD

**Issue by biopelayo** [griffithlab/VAtools#43]
Hi!

Trying to use your useful tool, I get this error for the 3rd argument. Not pretty sure how use it. My vcf is OK and the tsv is ok also. It seems that the INFO filed is not detected in the vcf... Any advice.

By the way, I will be possible to add more columns in the tsv file to collapse into the vcf ??

I paste the command and the error

 
`vcf-info-annotator -f 'String' --overwrite -o ./vatools_merge_test ./WES_tsv_rare.vcf ./rare_genes.txt INFO
`
Traceback (most recent call last):
  File "/home/geopela/.local/bin/vcf-info-annotator", line 8, in <module>
    sys.exit(main())
  File "/home/geopela/.local/lib/python3.8/site-packages/vatools/vcf_info_annotator.py", line 103, in main
    raise Exception("the --description and --value_format arguments are required unless updating/overwriting an existing field (with flag --overwrite)")
Exception: the --description and --value_format arguments are required unless updating/overwriting an existing field (with flag --overwrite)

**Comment by susannasiebert** [comment]
I believe there might be some confusion here since you are trying to use `INFO` as the info_field argument. This tool doesn't add a whole INFO column but rather one single INFO field. info_field is the identifier for the INFO field you want to add. So, for example, if your TSV contains a list of quality scores for each variant then you might want to call the field QUAL. Whatever you call your field, you will need to add a `--description` argument to your command list so that the tool can write an appropriate VCF header for your new field.

Unfortunately, right now the tool only supports a single value in your input TSV. You would need to create multiple input TSVs and run the tool consecutively using the VCF output file from previous tool runs as the input for subsequent runs. However, this is a feature we should absolutely add. Unfortunately, developer time is pretty limited right now so this will probably not get done for a while.

**Comment by susannasiebert** [comment]
In regards to your suggested feature addition, I created issue #46 to track development.

**Comment by biopelayo** [comment]
Thank you so much for the clarification! Very helpful!

**Comment by susannasiebert** [comment]
I take it you were able to get your command to run. I'll be closing this issue but do feel free to reopen (or make a new issue) if you're still running into trouble or have any additional questions.
