### ISSUE TITLE
VEP entry for at CHR chr*, POS *, REF *, ALT * already exists 

### ISSUE THREAD

**Issue by nliorni** [griffithlab/VAtools#57]
Greetings,

I am parsing a VEP annotated vcf file with the vep_annotation_reporter. My file may contain multiple rows of the same variant. The program stops when finds said repeated variant and prints:

VEP entry for at CHR chr*, POS *, REF *, ALT * already exists 

Is there a way I can parse this file with repeated variants or should I remove such variants?
Thank you.

**Comment by susannasiebert** [comment]
Hi @nliorni. I apologize for taking such a long time to getting back to your question. Yes, duplicate variants should be removed since they should be identical. Are there any actual differences in your example VCF between two variants? 

On our end we can downgrade this from an error to a warning and only process the first variant.

**Comment by susannasiebert** [comment]
This change has been implemented in version 5.1.0. Duplicate variants no longer result in an error downgrade but instead a warning is written to stdout and and onl the first variant is processed.
